#!/bin/bash
set -e

# Detect if running in interactive terminal
if [ -t 1 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

# Progress indicator functions
show_spinner() {
    local pid=$1
    local message=$2

    if [ "$INTERACTIVE" = true ]; then
        local spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
        local i=0
        tput civis 2>/dev/null || true
        while kill -0 $pid 2>/dev/null; do
            i=$(( (i+1) %10 ))
            printf "\r${spin:$i:1} $message"
            sleep 0.1
        done
        printf "\r"
        tput cnorm 2>/dev/null || true
    else
        # Non-interactive: just wait for process to complete
        wait $pid 2>/dev/null || true
    fi
}

show_progress() {
    local current=$1
    local total=$2
    local message=$3

    if [ "$INTERACTIVE" = true ]; then
        local width=30
        local percentage=$((current * 100 / total))
        local filled=$((width * current / total))

        printf "\r["
        printf "%${filled}s" | tr ' ' '='
        printf "%$((width - filled))s"
        printf "] %3d%% (%d/%d) %s" $percentage $current $total "$message"
    else
        # Non-interactive: print simple progress
        echo "  [$current/$total] $message"
    fi
}

# Cleanup function
cleanup() {
    if [ "$INTERACTIVE" = true ]; then
        tput cnorm 2>/dev/null || true
    fi
}
trap cleanup EXIT

# Skip setup if already completed
if [ -f ~/.setup-complete ]; then
    echo "✅ Setup already completed on: $(cat ~/.setup-complete)"
    echo "   To re-run setup, delete ~/.setup-complete and restart container"
    exit 0
fi

echo "🚀 Setting up Solidity development environment..."

# JetBrains uses /workspace as the mount point
WORKSPACE_DIR="/workspace"

echo "📍 Workspace: $WORKSPACE_DIR"

# Copy CLAUDE.md from mounted file (skip if already exists - migration case)
if [ -f "/tmp/claude-workflow.md" ]; then
    if [ -f "$WORKSPACE_DIR/CLAUDE.md" ]; then
        echo "📄 CLAUDE.md already exists - skipping (migration case)"
    else
        echo "📄 Copying CLAUDE.md..."
        cp /tmp/claude-workflow.md "$WORKSPACE_DIR/CLAUDE.md"
        echo "✅ CLAUDE.md copied to project root"
    fi
    fi

# Git configuration
if [ -n "${GIT_AUTHOR_NAME}" ] && [ -n "${GIT_AUTHOR_EMAIL}" ]; then
    echo "📝 Configuring Git..."
    (
        git config --global user.name "${GIT_AUTHOR_NAME}"
        git config --global user.email "${GIT_AUTHOR_EMAIL}"
        git config --global init.defaultBranch main
        git config --global pull.rebase false
    ) &
    show_spinner $! "Configuring Git..."
    echo "✅ Git configured"
fi

# Add .devcontainer files to .gitignore
if [ -f "$WORKSPACE_DIR/.gitignore" ]; then
    if ! grep -q "\.devcontainer/jetbrains_errors\.log" "$WORKSPACE_DIR/.gitignore"; then
        echo "" >> "$WORKSPACE_DIR/.gitignore"
        echo "# JetBrains IDE error logs (generated by dc nc --export)" >> "$WORKSPACE_DIR/.gitignore"
        echo ".devcontainer/jetbrains_errors.log" >> "$WORKSPACE_DIR/.gitignore"
        echo "✅ Added jetbrains_errors.log to .gitignore"
    fi
    if ! grep -q "\\.devcontainer/ports\\.json" "$WORKSPACE_DIR/.gitignore"; then
        echo "" >> "$WORKSPACE_DIR/.gitignore"
        echo "# Port tracking file (generated by dc tool)" >> "$WORKSPACE_DIR/.gitignore"
        echo ".devcontainer/ports.json" >> "$WORKSPACE_DIR/.gitignore"
        echo "✅ Added ports.json to .gitignore"
    fi
else
    # Create .gitignore if it doesn't exist
    cat > "$WORKSPACE_DIR/.gitignore" << 'EOF'
# JetBrains IDE error logs (generated by dc nc --export)
.devcontainer/jetbrains_errors.log

# Port tracking file (generated by dc tool)
.devcontainer/ports.json
EOF
    echo "✅ Created .gitignore with devcontainer files"
fi

# Node/Yarn setup
if command -v node &> /dev/null; then
    echo "📦 Setting up Yarn..."

    (
        # Create minimal package.json if it doesn't exist to pin Yarn version
        # Users can modify or replace this file as needed
        if [ ! -f "$WORKSPACE_DIR/package.json" ]; then
            cat > "$WORKSPACE_DIR/package.json" <<'EOF'
{
  "packageManager": "yarn@1.22.22"
}
EOF
        fi

        # Pre-download Yarn to cache it (avoids download prompts)
        corepack prepare yarn@1.22.22 --activate &>/dev/null

        # Configure Yarn to use node-modules instead of PnP
        cat > "$WORKSPACE_DIR/.yarnrc.yml" <<EOF
nodeLinker: node-modules
EOF
    ) &
    show_spinner $! "Setting up Yarn..."
    echo "✅ Yarn configured"
    echo "   - Node: $(node --version)"
    echo "   - Yarn: $(yarn --version)"
fi


# Prettier installation
if command -v yarn &> /dev/null && [ -f "$WORKSPACE_DIR/package.json" ]; then
    echo "🎨 Installing Prettier..."
    (
        cd "$WORKSPACE_DIR"
        yarn add -D prettier prettier-plugin-solidity &>/dev/null
    ) &
    show_spinner $! "Installing Prettier and prettier-plugin-solidity..."
    echo "✅ Prettier installed"
fi

# Install Foundry (always for Solidity)
echo "🔨 Installing Foundry..."
(
    curl -L https://foundry.paradigm.xyz | bash &>/dev/null
    export PATH="$HOME/.foundry/bin:$PATH"
    echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> ~/.bashrc
    echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> ~/.zshrc
    echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> ~/.profile
    echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> ~/.zprofile
    source ~/.bashrc || true
    foundryup
) &
show_spinner $! "Installing Foundry toolchain..."
echo "✅ Foundry installed"

# Claude Code installation
echo "🤖 Installing Claude Code..."
if curl -fsSL https://claude.ai/install.sh | bash > /tmp/claude-install.log 2>&1; then
    echo "✅ Claude Code installed"
else
    echo "⚠️  Claude Code installation failed (see /tmp/claude-install.log for details)"
    echo "   You can retry manually: curl -fsSL https://claude.ai/install.sh | bash"
fi

# Add Claude Code to PATH
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.profile
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zprofile

# Load Anthropic credentials from mounted config file
if [ -z "${ANTHROPIC_BASE_URL}" ] || [ -z "${ANTHROPIC_AUTH_TOKEN}" ]; then
    if [ -f "/tmp/anthropic-cred.sh" ]; then
        source /tmp/anthropic-cred.sh
    fi
fi

# Write credentials to shell configs
if [ -n "${ANTHROPIC_BASE_URL}" ]; then
    echo "export ANTHROPIC_BASE_URL=\"${ANTHROPIC_BASE_URL}\"" >> ~/.bashrc
    echo "export ANTHROPIC_BASE_URL=\"${ANTHROPIC_BASE_URL}\"" >> ~/.zshrc
fi

if [ -n "${ANTHROPIC_AUTH_TOKEN}" ]; then
    echo "export ANTHROPIC_AUTH_TOKEN=\"${ANTHROPIC_AUTH_TOKEN}\"" >> ~/.bashrc
    echo "export ANTHROPIC_AUTH_TOKEN=\"${ANTHROPIC_AUTH_TOKEN}\"" >> ~/.zshrc
fi

export PATH="$HOME/.local/bin:$PATH"

# Configure Claude Code settings
if [ -n "${ANTHROPIC_AUTH_TOKEN}" ] && [ -n "${ANTHROPIC_BASE_URL}" ]; then
    echo "⚙️  Configuring Claude Code..."
    mkdir -p ~/.claude
    cat > ~/.claude/settings.json <<EOF
{
  "env": {
    "ANTHROPIC_AUTH_TOKEN": "${ANTHROPIC_AUTH_TOKEN}",
    "ANTHROPIC_BASE_URL": "${ANTHROPIC_BASE_URL}",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": 1
  }
}
EOF
    echo "✅ Claude Code configured"
fi

# Codex installation
echo "🤖 Installing Codex..."
# Configure npm for user-level global installs (no sudo required)
npm config set prefix ~/.npm-global
mkdir -p ~/.npm-global
if npm install -g @openai/codex > /tmp/codex-install.log 2>&1; then
    echo "✅ Codex installed"
else
    echo "⚠️  Codex installation failed (see /tmp/codex-install.log for details)"
    echo "   You can retry manually: npm install -g @openai/codex"
fi

# Add npm global binaries to PATH
echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.bashrc
echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.profile
echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.zprofile

# Copy Codex configuration files
echo "⚙️  Configuring Codex..."
mkdir -p ~/.codex

if [ -f "/tmp/codex-agents.md" ]; then
    cp /tmp/codex-agents.md ~/.codex/AGENTS.md
    echo "✅ Codex AGENTS.md copied"
fi

if [ -f "/tmp/codex-auth.json" ]; then
    cp /tmp/codex-auth.json ~/.codex/auth.json
    chmod 600 ~/.codex/auth.json  # Protect auth file
    echo "✅ Codex auth.json copied"
fi

if [ -f "/tmp/codex-config.toml" ]; then
    cp /tmp/codex-config.toml ~/.codex/config.toml
    echo "✅ Codex config.toml copied"
fi

# SSH server configuration
echo "🔐 Configuring SSH server..."
(
    # Create SSH directory
    mkdir -p ~/.ssh

    # Copy authorized_keys from mounted file
    if [ -f "/tmp/ssh-authorized-keys" ]; then
        cp /tmp/ssh-authorized-keys ~/.ssh/authorized_keys
    fi

    # Create SSH config for GitHub (port 443 for firewall compatibility)
    cat > ~/.ssh/config <<'EOF'
# ========================================
# GitHub (Custom Port)
# ========================================
Host github.com
    Hostname ssh.github.com
    Port 443
    User git
EOF

    # Set correct permissions AFTER all file operations
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/config
    chmod 600 ~/.ssh/authorized_keys 2>/dev/null || true

) &>/dev/null
echo "✅ SSH keys configured"

# Start SSH service
if ps -p 1 -o comm= | grep -q systemd; then
    # systemd is PID 1 (actually running)
    sudo systemctl enable ssh >/dev/null 2>&1 || true
    sudo systemctl start ssh >/dev/null 2>&1 || true
    echo "✅ SSH service started (systemd)"
else
    # Fallback for non-systemd containers (sysvinit)
    sudo update-rc.d ssh defaults >/dev/null 2>&1 || true
    sudo update-rc.d ssh enable >/dev/null 2>&1 || true
    sudo service ssh start >/dev/null 2>&1 || sudo /usr/sbin/sshd >/dev/null 2>&1 || true
    echo "✅ SSH service started (service)"
fi

# ⚠️  WARP SHELL INTEGRATION WARNING ⚠️
# The following Warp terminal integration hooks are based on Warp's official documentation
# as of 2025-12. These commands may change in future Warp versions.
# Official source: https://docs.warp.dev/features/subshells-and-shells
#
# If Warp terminal fails to detect shell integration in the future, check:
# 1. Warp's latest documentation for updated integration commands
# 2. Remove outdated hooks and replace with new ones
# 3. File location: templates/web3/solidity/.devcontainer/setup.sh

echo "🚀 Configuring Warp shell integration..."

# Add Warp integration hook to bash shell
cat >> ~/.bashrc <<'EOF'

# Warp terminal shell integration (added by dc devcontainer template)
# Warning: This may need updating in future Warp versions
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash"}}\x9c'
EOF
echo "✅ Warp integration added to ~/.bashrc"

# Add Warp integration hook to zsh shell
cat >> ~/.zshrc <<'EOF'

# Warp terminal shell integration (added by dc devcontainer template)
# Warning: This may need updating in future Warp versions
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'
EOF
echo "✅ Warp integration added to ~/.zshrc"

# ⚠️  GHOSTTY TERMINAL SUPPORT WARNING ⚠️
# The following Ghostty terminal configuration is based on Ghostty's terminfo requirements
# as of 2025-01. If Ghostty terminal displays incorrectly in future versions:
# 1. Check if terminfo needs updating: infocmp -x xterm-ghostty
# 2. Update terminfo source file in repository: terminfo/xterm-ghostty.terminfo
# 3. Ensure COLORTERM=truecolor is set in both shell configs and devcontainer.json
# 4. File location: templates/web3/solidity/.devcontainer/setup.sh

echo "🎨 Configuring Ghostty terminal support..."

# Install Ghostty terminfo to user's terminfo database
if [ -f "/tmp/xterm-ghostty.terminfo" ]; then
    mkdir -p ~/.terminfo/x
    cp /tmp/xterm-ghostty.terminfo ~/.terminfo/x/xterm-ghostty
    echo "✅ Ghostty terminfo installed"
else
    echo "⚠️  Ghostty terminfo not found (skipping)"
fi

# Add COLORTERM=truecolor to bash shell
cat >> ~/.bashrc <<'EOF'

# Ghostty terminal support (added by dc devcontainer template)
export COLORTERM=truecolor
EOF
echo "✅ COLORTERM=truecolor added to ~/.bashrc"

# Add COLORTERM=truecolor to zsh shell
cat >> ~/.zshrc <<'EOF'

# Ghostty terminal support (added by dc devcontainer template)
export COLORTERM=truecolor
EOF
echo "✅ COLORTERM=truecolor added to ~/.zshrc"

# ═══════════════════════════════════════════════════════════════════════════════
# Starship + ble.sh Terminal Enhancement
# ═══════════════════════════════════════════════════════════════════════════════

# ⚠️  STARSHIP + BLE.SH WARNING ⚠️
# The following configurations provide advanced terminal enhancements as of 2025-01.
# If behavior changes in future versions:
#
# Starship:
# 1. Check documentation: https://starship.rs
# 2. Verify initialization command format
# 3. Ensure STARSHIP_CONFIG environment variable is properly set
# 4. File location: templates/web3/solidity/.devcontainer/setup.sh
#
# ble.sh (Bash Line Editor):
# 1. Check documentation: https://github.com/akinomyoga/ble.sh
# 2. Verify installation method (git clone + make install)
# 3. Ensure sourcing happens AFTER starship init in ~/.bashrc
# 4. ble.sh only enhances bash (zsh users rely on native features)

echo ""
echo "⭐ Configuring Starship prompt..."

# Install Starship if not already present
if ! command -v starship &> /dev/null; then
    (
        curl -sS https://starship.rs/install.sh | sh -s -- -y &>/dev/null
    ) &
    show_spinner $! "Installing Starship..."
    echo "✅ Starship installed"
else
    echo "✅ Starship already installed"
fi

# Copy starship config from mounted location
if [ -f "/tmp/starship.toml" ]; then
    mkdir -p ~/.config/starship
    cp /tmp/starship.toml ~/.config/starship/starship.toml
    chmod 644 ~/.config/starship/starship.toml
    echo "✅ Starship config installed from host"
else
    echo "⚠️  Starship config not found at /tmp/starship.toml"
    echo "   Starship will use default configuration"
    echo "   To use custom config, ensure ~/.config/starship/starship.toml exists on host"
fi

echo ""
echo "📝 Installing ble.sh (Bash Line Editor)..."

# Install ble.sh for enhanced bash experience (bash only, not needed for zsh)
if [ ! -d ~/.local/share/blesh ]; then
    (
        git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git /tmp/ble.sh &>/dev/null
        cd /tmp/ble.sh
        make install PREFIX=~/.local &>/dev/null
        rm -rf /tmp/ble.sh
    ) &
    show_spinner $! "Installing ble.sh..."
    echo "✅ ble.sh installed"
else
    echo "✅ ble.sh already installed"
fi

# Configure ble.sh in bash (IMPORTANT: Must be sourced EARLY in shell initialization)
cat >> ~/.bashrc <<'EOF'

# ble.sh - Bash Line Editor (added by devcontainer template)
# Provides syntax highlighting, autosuggestions, and enhanced completion
# Note: Must be sourced early in shell initialization for best compatibility
[[ $- == *i* ]] && source ~/.local/share/blesh/ble.sh
EOF
echo "✅ ble.sh configured in ~/.bashrc"

# Note: ble.sh is bash-specific, zsh has native features (syntax-highlighting, autosuggestions)
echo "ℹ️  ble.sh enhances bash only (zsh users rely on native features)"

# Configure Starship initialization in bash (after ble.sh)
cat >> ~/.bashrc <<'EOF'

# Starship prompt (added by devcontainer template)
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init bash)"
EOF
echo "✅ Starship initialized in ~/.bashrc"

# Configure Starship initialization in zsh
cat >> ~/.zshrc <<'EOF'

# Starship prompt (added by devcontainer template)
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"
EOF
echo "✅ Starship initialized in ~/.zshrc"

# Summary
echo ""
echo "✅ Solidity environment setup complete!"
echo ""
echo "📌 Environment:"
[ -n "$(command -v node)" ] && echo "   - Node: $(node --version)"
[ -n "$(command -v yarn)" ] && echo "   - Yarn: $(yarn --version)"
[ -n "$(command -v forge)" ] && echo "   - Foundry: $(forge --version | head -1)"
[ -n "$(command -v codex)" ] && echo "   - Codex: $(codex --version)"
[ -n "$(command -v claude)" ] && echo "   - Claude Code: $(claude --version)"
[ -n "$(command -v starship)" ] && echo "   - Starship: $(starship --version | head -n1)"
[ -n "${GIT_AUTHOR_NAME}" ] && echo "   - Git: ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>"
echo ""

# Mark setup as complete
touch ~/.setup-complete
echo "$(date)" > ~/.setup-complete
